add arch linux install
pop-os/cosmic-epoch pull request #119
Opened 2023-06-24 06:11 UTC by soloturn

add arch linux install to README, to avoid people going through the lengthy install process there.

2023-06-26 07:34 UTC, rexhent requested changes
You accidentally doubled the link in line 121

2023-07-24 07:18 UTC, soloturn commented
thanks for the review, @rexhent ! i guess i divorce [helix](https://github.com/helix-editor/helix) editor on xfce terminal, as it double pastes *grrrr*

2023-11-02 00:59 UTC, soloturn commented
would you mind merging this or something is missing, @rexhent @Drakulix ?

2023-11-02 11:07 UTC, Drakulix commented on README.md
> +Currently an incomplete **pre-alpha**. Standard Installation is available for Pop!_OS, Arch Linux and its decendents, like Manjaro.
I don't mind having specific instructions for some distributions, but in general the systemd-sysext method works on a lot of distributions for testing. Which is all this should be used for right now. So please drop or adjust this line.

```suggestion
Currently an incomplete **pre-alpha**. Testing instructions below for various distributions.
```

2023-11-02 11:07 UTC, Drakulix commented on README.md
> +## Setup without package
```suggestion
## Setup on distributions without packaging of cosmic components
```

2023-11-02 11:07 UTC, Drakulix commented on README.md
> +For a more detailled discussion consider the [relevant section in the Arch wiki](https://wiki.archlinux.org/title/COSMIChttps://wiki.archlinux.org/title/COSMIC).
This seems like a copy&paste error?

```suggestion
For a more detailled discussion consider the [relevant section in the Arch wiki](https://wiki.archlinux.org/title/COSMIC).
```

2023-11-06 06:16 UTC, soloturn commented
cool, first time i saw edit pull request and commit on web ...

2023-11-06 08:15 UTC, Drakulix approved these changes
Thanks!

2023-11-06 08:15 UTC, merged