Clarify README
pop-os/cosmic-epoch pull request #503
Opened 2024-08-08 18:43 UTC by steelswords

Minor tweaks for readability

2024-08-08 20:18 UTC, jacobgkau requested changes
Other than the changes I'm requesting, I agree with the improvements.

2024-08-08 20:18 UTC, jacobgkau commented on README.md
> +Change to `WaylandEnable` to `true`:
Drop the first `to`:

> Change `WaylandEnable` to `true`:

2024-08-08 20:18 UTC, jacobgkau commented on README.md
> +Look for `LABEL="gdm_prefer_xorg"` and `LABEL="gdm_disable_wayland"`. Add `#` to the `RUN` statements so they look like this
I'd suggest adding a colon after `this` so it's `this:`.

2024-08-09 02:59 UTC, steelswords commented
Good suggestions! Done.

2024-08-30 01:30 UTC, mmstick approved these changes

2024-08-30 01:30 UTC, merged